Repository Smelser-Squad/Nile, pull requests merged in 2021-04, with the labels that each got.

#11 Created product dao
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
Labels: enhancement

#12 app properties DB setup
  nile-backend/src/main/resources/application.properties
Labels: enhancement

#13 Type model
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/Type.java
Labels: enhancement

#15 Spec model
  nile-backend/src/main/java/com/tp/Nile/models/Specification.java
Labels: enhancement

#17 Product service
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvaildProductIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullProductIdException.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
Labels: enhancement

#22 Created backend model for Order.
  nile-backend/src/main/java/com/tp/Nile/models/Order.java
Labels: enhancement

#21 added review model and began on tests
  nile-backend/build.gradle
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/test/java/com/tp/Nile/models/ReviewTest.java
Labels: enhancement

#23 Created components folder and MoreProducts initial files.
  nile-frontend/package-lock.json
  nile-frontend/src/App.js
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.js
Labels: enhancement

#31 Added Relationships to model
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/models/Photo.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/models/ProductTest.java
Labels: enhancement

#41 Fixing backend
  Dockerfile
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/models/Answer.java
  nile-backend/src/main/java/com/tp/Nile/models/Category.java
  nile-backend/src/main/java/com/tp/Nile/models/Feature.java
  nile-backend/src/main/java/com/tp/Nile/models/Order.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/Question.java
  nile-backend/src/main/java/com/tp/Nile/models/Review.java
  nile-backend/src/main/java/com/tp/Nile/models/Specification.java
  nile-backend/src/main/java/com/tp/Nile/models/Type.java
  nile-backend/src/main/java/com/tp/Nile/models/User.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/resources/application.properties
  nile-backend/src/test/java/com/tp/Nile/models/ReviewTest.java
Labels: bug

#50 Cart frontend
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ReviewRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ReviewServiceImpl.java
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/public/index.html
  nile-frontend/src/App.css
  nile-frontend/src/App.js
  nile-frontend/src/App.test.js
  nile-frontend/src/components/Checkout/Checkout.css
  nile-frontend/src/components/Checkout/Checkout.js
  nile-frontend/src/components/Header/Header.css
  nile-frontend/src/components/Header/Header.js
  nile-frontend/src/components/Home/Home.css
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/index.css
  nile-frontend/src/index.js
  nile-frontend/src/logo.svg
  nile-frontend/src/setupTests.js
Labels: enhancement

#52 Product specification model w/ composite key
  nile-backend/src/main/java/com/tp/Nile/models/ProductSpecification.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductSpecificationId.java
  nile-backend/src/main/java/com/tp/Nile/models/Specification.java
Labels: enhancement

#57 Specification service
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidSpecIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullSpecIdException.java
  nile-backend/src/main/java/com/tp/Nile/repositories/SpecificationRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationService.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationServiceImpl.java
Labels: enhancement

#64 Product photo modal
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-frontend/package-lock.json
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.css
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
Labels: enhancement

#66 More products frame
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.js
Labels: enhancement

#62 Cart frontend new
  nile-backend/src/main/java/com/tp/Nile/models/Order.java
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/App.js
  nile-frontend/src/StateProvider.js
  nile-frontend/src/components/Cart/Checkout/Checkout.css
  nile-frontend/src/components/Cart/Checkout/Checkout.js
  nile-frontend/src/components/Cart/Subtotal/Subtotal.css
  nile-frontend/src/components/Cart/Subtotal/Subtotal.js
  nile-frontend/src/components/Header/Header.js
  nile-frontend/src/components/Home/Home.css
  nile-frontend/src/index.js
  nile-frontend/src/reducer.js
Labels: enhancement

#71 Product controller
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/requests/AddProductRequest.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidPriceException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidTypeIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidVendorIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullBrandException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullDescriptionException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullNameException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullPriceException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullProductObjectException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullTypeIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullVendorIdException.java
  nile-backend/src/main/java/com/tp/Nile/models/Feature.java
  nile-backend/src/main/java/com/tp/Nile/models/Photo.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/Review.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ReviewRepository.java
  nile-backend/src/main/java/com/tp/Nile/repositories/TypeRepository.java
  nile-backend/src/main/java/com/tp/Nile/repositories/VendorRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/ReviewService.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeService.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/VendorService.java
  nile-backend/src/main/java/com/tp/Nile/services/VendorServiceImpl.java
  nile-backend/src/main/resources/application.properties
Labels: enhancement

#77 Added single product listing page and routing.
  nile-frontend/src/App.js
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/MoreProducts/Product.js
  nile-frontend/src/components/ProductListing/SingleProductListing.css
  nile-frontend/src/components/ProductListing/SingleProductListing.js
Labels: enhancement

#81 Add product
  nile-backend/build.gradle
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/TypeController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/VendorController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/requests/AddProductRequest.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidPhotoIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/NullPhotoIdException.java
  nile-backend/src/main/java/com/tp/Nile/models/Answer.java
  nile-backend/src/main/java/com/tp/Nile/models/Category.java
  nile-backend/src/main/java/com/tp/Nile/models/Order.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductOrder.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductPhoto.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductSpecification.java
  nile-backend/src/main/java/com/tp/Nile/models/Question.java
  nile-backend/src/main/java/com/tp/Nile/models/Review.java
  nile-backend/src/main/java/com/tp/Nile/models/Specification.java
  nile-backend/src/main/java/com/tp/Nile/models/Type.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoService.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeService.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/VendorService.java
  nile-backend/src/main/java/com/tp/Nile/services/VendorServiceImpl.java
Labels: enhancement

#82 Products are shown and styled in the front page
  nile-frontend/src/App.js
  nile-frontend/src/components/Home/Home.css
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.css
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.js
  nile-frontend/src/index.css
Labels: enhancement

#84 More product grid
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/components/MoreProducts/Product.css
Labels: enhancement

#88 Product photos service
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/QAController.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvaildProductIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvaildQAIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidProductIdException.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/InvalidQAIdException.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/CategoryService.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoService.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/QAService.java
  nile-backend/src/main/java/com/tp/Nile/services/QAServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-frontend/src/App.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.css
Labels: enhancement

#91 React product component
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.css
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#93 Uniform api calls on most controllers
  nile-backend/src/main/java/com/tp/Nile/controllers/CategoryController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/FeatureController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/OrderController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/SpecificationController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/TypeController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/VendorController.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationService.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeService.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
Labels: enhancement

#85 Type service more methods
  nile-frontend/src/components/Header/Header.js
  nile-frontend/src/components/Home/Home.css
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/reducer.js
Labels: enhancement

#83 Spec controller
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/SpecificationController.java
Labels: enhancement

#92 More product grid
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.js
Labels: enhancement

#101 Review frontend
  nile-backend/build.gradle
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/Reviews/Reviews.css
  nile-frontend/src/components/Reviews/Reviews.js
  nile-frontend/src/components/Reviews/SingleReview.css
  nile-frontend/src/components/Reviews/SingleReview.js
Labels: enhancement

#98 Product photo frontend
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-backend/src/main/resources/application-dev.properties
  nile-frontend/src/App.js
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.css
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
Labels: enhancement

#103 Type model testing
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/models/TypeTest.java
Labels: enhancement

#104 React product component
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/requests/AddProductRequest.java
  nile-backend/src/main/java/com/tp/Nile/models/Feature.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductPhoto.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoService.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-frontend/package-lock.json
Labels: bug

#105 Show cart
  nile-frontend/.vscode/settings.json
  nile-frontend/package-lock.json
  nile-frontend/src/App.js
  nile-frontend/src/components/Cart/CartProduct/CartProduct.css
  nile-frontend/src/components/Cart/CartProduct/CartProduct.js
  nile-frontend/src/components/Cart/Checkout/Checkout.js
  nile-frontend/src/components/Cart/Subtotal/Subtotal.css
  nile-frontend/src/components/Cart/Subtotal/Subtotal.js
  nile-frontend/src/components/Checkout/Checkout.css
  nile-frontend/src/components/Checkout/Checkout.js
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/ReviewSummary/ReviewSummary.jsx
  nile-frontend/src/reducer.js
Labels: enhancement

#109 More products data
  nile-frontend/src/components/MoreProducts/MoreProducts.js
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
Labels: enhancement

#132 Vendor testing
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/VendorController.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/VendorServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/models/CategoryTest.java
  nile-backend/src/test/java/com/tp/Nile/models/VendorTest.java
  nile-backend/src/test/java/com/tp/Nile/services/VendorServiceImplTests.java
  nile-frontend/src/App.js
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/service/PhotoService.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#140 More products axios
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.jsx
Labels: enhancement

#146 Spec service testing, small changes to spec and type controllers and services
  nile-backend/src/main/java/com/tp/Nile/controllers/SpecificationController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/TypeController.java
  nile-backend/src/main/java/com/tp/Nile/exceptions/MissingPropertyException.java
  nile-backend/src/main/java/com/tp/Nile/models/Product.java
  nile-backend/src/main/java/com/tp/Nile/models/ProductSpecification.java
  nile-backend/src/main/java/com/tp/Nile/models/Specification.java
  nile-backend/src/main/java/com/tp/Nile/repositories/SpecificationRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationService.java
  nile-backend/src/main/java/com/tp/Nile/services/SpecificationServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/TypeServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/controllers/ProductControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/controllers/integration/ProductControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/models/TypeTest.java
  nile-backend/src/test/java/com/tp/Nile/models/UserTest.java
  nile-backend/src/test/java/com/tp/Nile/services/SpecificationServiceImplTests.java
Labels: enhancement

#154 fixed review front end. now shows reviews on associated product page
  nile-backend/src/main/java/com/tp/Nile/controllers/ReviewController.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ReviewRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ReviewService.java
  nile-backend/src/main/java/com/tp/Nile/services/ReviewServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/services/ReviewServiceImplTests.java
  nile-frontend/src/App.js
  nile-frontend/src/components/Reviews/CreateReview.css
  nile-frontend/src/components/Reviews/CreateReview.js
  nile-frontend/src/components/Reviews/Reviews.css
  nile-frontend/src/components/Reviews/Reviews.js
  nile-frontend/src/components/Reviews/SingleReview.css
  nile-frontend/src/service/ReviewService.js
  package-lock.json
Labels: enhancement

#155 Color radio buttons
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/controllers/requests/AddProductRequest.java
  nile-backend/src/main/java/com/tp/Nile/models/Vendor.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/PhotoService.java
  nile-backend/src/test/java/com/tp/Nile/models/CategoryTest.java
  nile-backend/src/test/java/com/tp/Nile/models/UserTest.java
  nile-backend/src/test/java/com/tp/Nile/models/VendorTest.java
  nile-backend/src/test/java/com/tp/Nile/services/VendorServiceImplTests.java
  nile-frontend/src/App.js
  nile-frontend/src/components/Home/Home.css
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.css
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/service/PhotoService.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#156 Review tag component
  nile-backend/src/test/java/com/tp/Nile/models/UserTest.java
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/App.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.css
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ReviewTag/Tag.jsx
  nile-frontend/src/components/Reviews/Reviews.js
Labels: enhancement

#160 More products navigation
  nile-backend/src/test/java/com/tp/Nile/models/UserTest.java
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/MoreProducts/MoreProducts.css
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.jsx
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
Labels: enhancement

#162 Product spec controller
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductSpecificationController.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductSpecificationServiceImpl.java
Labels: enhancement

#164 Uncommented cart and user tests. Debugged tests to passing.
  nile-backend/src/main/java/com/tp/Nile/controllers/UserController.java
  nile-backend/src/main/java/com/tp/Nile/models/Category.java
  nile-backend/src/main/java/com/tp/Nile/models/Feature.java
  nile-backend/src/main/java/com/tp/Nile/models/Review.java
  nile-backend/src/main/java/com/tp/Nile/models/User.java
  nile-backend/src/main/java/com/tp/Nile/services/CartServiceImpl.java
  nile-backend/src/main/java/com/tp/Nile/services/UserServiceImpl.java
  nile-backend/src/test/java/com/tp/Nile/controllers/CartControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/controllers/CategoryControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/controllers/FeatureControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/controllers/UserControllerTest.java
  nile-backend/src/test/java/com/tp/Nile/services/UserServiceImplTests.java
Labels: enhancement

#166 Magnifier modal
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductPhotoService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductPhotoServiceImpl.java
  nile-backend/src/main/resources/application-dev.properties
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/components/ProductPhotos/ProductPhotos.css
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
Labels: enhancement

#169 Create review page
  nile-frontend/src/App.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.css
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ReviewSummary/ReviewSummary.jsx
  nile-frontend/src/components/Reviews/CreateReview.js
  nile-frontend/src/components/Reviews/Reviews.js
  nile-frontend/src/components/Reviews/SingleReview.js
  nile-frontend/src/service/ReviewService.js
Labels: enhancement

#170 Review tag component
  nile-backend/src/main/resources/application-dev.properties
  nile-frontend/package-lock.json
  nile-frontend/package.json
  nile-frontend/src/App.js
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ReviewTag/Tag.jsx
  nile-frontend/src/components/Reviews/Reviews.js
  package-lock.json
  package.json
Labels: enhancement

#167 Brand products
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductPhotoService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductPhotoServiceImpl.java
  nile-frontend/src/App.js
  nile-frontend/src/components/Brand/BrandProducts.css
  nile-frontend/src/components/Brand/BrandProducts.jsx
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/service/PhotoService.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#173 Review tag component
  nile-frontend/src/components/ReviewTag/Tag.css
  nile-frontend/src/components/ReviewTag/Tag.jsx
Labels: enhancement

#177 More products category query
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-frontend/src/components/Brand/BrandProducts.jsx
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/MoreProducts/Product.css
  nile-frontend/src/components/MoreProducts/Product.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/service/PhotoService.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#179 Create review working
  nile-frontend/.vscode/launch.json
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ReviewSummary/ReviewSummary.jsx
  nile-frontend/src/components/Reviews/CreateReview.css
  nile-frontend/src/components/Reviews/CreateReview.js
  nile-frontend/src/components/Reviews/Reviews.js
  nile-frontend/src/service/ReviewService.js
Labels: enhancement

#184 Create review page styling
  nile-frontend/src/components/Reviews/CreateReview.css
  nile-frontend/src/components/Reviews/CreateReview.js
  nile-frontend/src/components/Reviews/Reviews.js
Labels: Styling

#191 Magnifier modal
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-backend/src/main/java/com/tp/Nile/controllers/ProductPhotoController.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductPhotoRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductPhotoServiceImpl.java
  nile-frontend/package.json
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/service/PhotoService.jsx
Labels: enhancement

#195 Update data-dev.sql
  nile-backend/src/main/resources/data-dev.sql
Labels: bug
