Repository Smelser-Squad/Nile, pull requests merged in 2021-05, with the labels that each got.

#200 All reviews component
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-frontend/src/App.js
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ReviewTag/Tag.jsx
  nile-frontend/src/components/Reviews/Reviews.js
  nile-frontend/src/components/Reviews/ShowAllReviews.css
  nile-frontend/src/components/Reviews/ShowAllReviews.js
Labels: enhancement

#201 Comparison table styling
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-frontend/package-lock.json
  nile-frontend/src/components/Comparison/Comparison.jsx
  nile-frontend/src/components/Comparison/Table.css
  nile-frontend/src/components/Comparison/Table.jsx
Labels: enhancement

#203 More products pages
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/components/MoreProducts/Product.jsx
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/components/ReviewSummary/ReviewSummary.jsx
  nile-frontend/src/service/ReviewService.js
Labels: enhancement

#204 More products pages
  nile-frontend/src/components/MoreProducts/MoreProducts.jsx
  nile-frontend/src/service/ProductService.jsx
Labels: enhancement

#206 React stars and images working in comparison table
  nile-frontend/src/components/Comparison/Comparison.jsx
  nile-frontend/src/components/Comparison/Table.css
  nile-frontend/src/components/Comparison/Table.jsx
  nile-frontend/src/service/ReviewService.js
Labels: enhancement

#209 All reviews component
  nile-frontend/src/components/ProductListing/SingleProductListing.css
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/Reviews/ShowAllReviews.css
  nile-frontend/src/components/Reviews/ShowAllReviews.js
Labels: enhancement

#210 Filter brand products
  nile-backend/src/main/java/com/tp/Nile/config/SecurityConfig.java
  nile-backend/src/main/java/com/tp/Nile/repositories/ProductRepository.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductService.java
  nile-backend/src/main/java/com/tp/Nile/services/ProductServiceImpl.java
  nile-frontend/package-lock.json
  nile-frontend/src/App.js
  nile-frontend/src/components/Brand/BrandProducts.css
  nile-frontend/src/components/Brand/BrandProducts.jsx
  nile-frontend/src/components/Cart/CartProduct/CartProduct.js
  nile-frontend/src/components/Cart/Subtotal/Subtotal.js
  nile-frontend/src/components/Checkout/Checkout.js
  nile-frontend/src/components/Home/Home.js
  nile-frontend/src/components/Home/HomeProduct.js
  nile-frontend/src/components/ProductColorSelector/ProductColorSelector.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
  nile-frontend/src/components/ProductPhotos/ProductPhotos.jsx
  nile-frontend/src/components/SignUp/index.js
  nile-frontend/src/service/PhotoService.jsx
Labels: enhancement

#212 conditional render
  nile-frontend/src/components/Reviews/ShowAllReviews.js
Labels: Styling

#221 Comparison modal finally working, option to display only appears if there is more than one products of the current type
  nile-frontend/src/components/Comparison/Comparison.css
  nile-frontend/src/components/Comparison/Comparison.jsx
  nile-frontend/src/components/Comparison/PopUp.css
  nile-frontend/src/components/Comparison/PopUp.jsx
  nile-frontend/src/components/Comparison/Table.css
  nile-frontend/src/components/Comparison/Table.jsx
Labels: Styling

#223 All reviews component
  nile-frontend/src/components/ReviewTag/Tag.jsx
  nile-frontend/src/components/Reviews/Reviews.js
Labels: enhancement

#226 Pagination brand products
  nile-frontend/src/App.js
  nile-frontend/src/components/Brand/AllBrandProducts.jsx
  nile-frontend/src/components/Brand/BrandProduct.jsx
  nile-frontend/src/components/Brand/BrandProducts.jsx
  nile-frontend/src/components/ProductListing/SingleProductListing.js
Labels: enhancement

#230 Can navigate to products through comparison table
  nile-frontend/src/components/Comparison/Comparison.css
  nile-frontend/src/components/Comparison/Comparison.jsx
  nile-frontend/src/components/Comparison/PopUp.jsx
  nile-frontend/src/components/Comparison/Table.css
  nile-frontend/src/components/Comparison/Table.jsx
Labels: enhancement

#236 Brand products filter
  nile-frontend/src/components/Brand/AllBrandProducts.jsx
  nile-frontend/src/components/Brand/BrandProduct.jsx
  nile-frontend/src/components/Cart/Subtotal/Subtotal.js
  nile-frontend/src/components/Checkout/Checkout.js
  nile-frontend/src/components/Payment/Payment.js
Labels: enhancement

#246 All reviews component
  nile-frontend/src/components/ReviewTag/Tag.jsx
  nile-frontend/src/components/Reviews/ShowAllReviews.js
Labels: Styling

#247 Comparison hotfix
  nile-frontend/src/components/Comparison/Comparison.jsx
Labels: bug

#248 Brand products styling
  nile-frontend/src/components/Brand/AllBrandProducts.jsx
  nile-frontend/src/components/Brand/BrandProduct.jsx
  nile-frontend/src/components/Brand/BrandProducts.css
  nile-frontend/src/components/ProductListing/SingleProductListing.js
Labels: enhancement
